version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    assignees:
      - ChangkeunJ
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    assignees:
      - ChangkeunJ
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
